name: Mirror to Codeberg

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/blackwew/cocotier.ro.git"
          GIT_USERNAME: blackwew
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
