name: Mirror to Codeberg

on: [push]

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        run: |
          git fetch --update-head-ok origin "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
          git push --prune "https://blackwew:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/blackwew/cocotier.ro.git" "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
